config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
  resources :personality_tests, only: [ :new, :create, :show ]
  resources :posts, only: [ :index, :new, :create, :edit, :show, :edit, :update, :destroy ]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.erb
<div class="flex flex-col items-center justify-center  text-center space-y-3 px-4 md:px-8 mt-9">
  <p class="text-6xl font-extrabold text-gray-800">名僧マッチ</p>
  <p class="text-lg font-medium text-gray-600">簡単診断であなたに合う名僧たちに出会う</p>
  <p class="text-lg font-medium text-gray-600">ユーザ登録であなたの体験を共有</p>
  <%= image_tag "22225678.png", alt: "トップ画面僧侶", class: "w-full max-w-md py-4" %>
 
  <div class="mt-9"> 
    <%= link_to "診断する", new_personality_test_path, class: "inline-block bg-blue-300 hover:bg-blue-400 text-black font-semibold py-3 px-6 rounded-md shadow-md transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-50" %>
  </div>
</div>