config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
  resources :personality_tests, only: [ :new, :create, :show ]
  resources :posts, only: [ :index, :new, :create, :edit, :show, :edit, :update, :destroy ]
end

app/models/personality_test.rb
class PersonalityTest
  include ActiveModel::Model
  attr_accessor :answers

  def calculate_score
    score = 0
    questions = Question.all
    questions.each do |question|
      answer = answers[question.id.to_s]
      if answer
        score_mapping = question.score_mappings.find_by(option: answer.to_i)
        score += score_mapping.score if score_mapping
      end
    end
    score
  end

  def get_result
    total_score = calculate_score
    Monk.find_by("start_score <= ? AND end_score >= ?", total_score, total_score)
  end
end

app/controllers/personality_tests_controller.rb
class PersonalityTestsController < ApplicationController
  def new
    @questions = Question.order(:id)
    @personality_test = PersonalityTest.new
  end

  def create
    @personality_test = PersonalityTest.new(personality_test_params)
    @result = @personality_test.get_result

    if @result
      session[:result] = @result.id
      redirect_to personality_test_path(@result.id)
    else
      flash[:alert] = "診断結果の取得に失敗しました。"
      render :new
    end
  end

  def show
    @result = Monk.find_by(id: session[:result])
    unless @result
      redirect_to new_personality_test_path
    end
  end

  private

  def personality_test_params
    params.require(:personality_test).permit(answers: {})
  end
end

app/views/personality_tests/new.html.erb
<div class="gradation-image object-contain">
  <%= form_with model: @personality_test, url: personality_tests_path, method: :post, data: { turbo: false } do |f| %>
    <div class="text-center max-w-2xl mx-auto p-6 bg-gray-90 shadow-md rounded-lg mt-10" data-controller="step-form">
      <% @questions.each_with_index do |question, index| %>
        <div id="step<%= index + 1 %>"
             class="flex flex-col justify-center items-center space-y-6 <%= index.zero? ? '' : 'hidden' %>"
             data-step-form-target="step">

          <div class="text-center text-lg font-bold text-gray-700">
            <p>第<%= index + 1 %>/12問</p>
          </div>

          <div class="text-center">
            <%= f.label "answers[#{ question.id }]", question.content, class: "block text-lg font-semibold text-gray-700" %>
          </div>

          <div class="flex justify-between items-center w-full mt-4 text-sm text-gray-600">
            <p class="text-gray-600">当てはまらない</p>
            <p class="text-gray-600"></p>
            <p class="text-gray-600">当てはまる</p>
          </div>

          <div id="radios" class="relative fustify-center items-center space-x-5 mt-2">
            <% question.score_mappings.each do |mapping| %>
              <%= radio_button_tag "personality_test[answers][#{ question.id }]", mapping.option, false,
                class: "form-radio h-6 w-6 text-indigo-500 focus:ring-indigo-400 focus:ring-offset-2",
                data: { action: "change->step-form#autoNext" } %>
            <% end %>
          </div>

          <div class="flex justify-between w-full items-center mt-6">
            <% if index.positive? %>
              <button type="button" data-action="step-form#prevStep"
                class="px-4 py-2 bg-gray-300 text-gray-700 rounded-md hover:bg-gray-400 focus:outline-none focus:ring-2 focus:ring-gray-400">
                戻る
              </button>
            <% end %>
            
            <% if index == @questions.size - 1 %>
              <%= f.submit "診断する",
                class: "px-6 py-2 inline-block bg-blue-200 hover:bg-blue-400 text-black font-semibold py-3 px-6 rounded-md shadow-md transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-50'",  data: { action: "step-form#submitForm" } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/personality_tests/show.html.erb
<div class="max-w-4xl mx-auto p-6 bg-gray-90 rounded-lg shadow-lg border border-gray-200 mt-8">
  <h1 class="animation-fadeIn1 text-5xl font-semibold text-center text-gray-800 mb-4">診断結果</h1>
  <div class="animation-fadeIn2">
    <div class=" flex justify-center mb-6">
      <%= image_tag @result.image_path, alt: "診断結果画像", class: "w-64 h-64 object-cover rounded-full border-4 border-gray-200 shadow-md", style: " object-position: center 10%;" %>
    </div>

    <div class="text-center">
      <p class="text-2xl font-bold text-gray-900 mb-2">
        <%= @result.name %>
      </p>
      <p class="text-lg font-medium text-gray-900 mb-2">
        <%= @result.title %>
      </p>
      <p class="text-lg font-medium text-black-900 mb-2">
        <%= @result.description %>
      </p>
      <p class="text-lg font-semibold text-gray-900 mb-2 mt-6">
        <%= @result.name %>とは
      </p>
      <p class="text-lg font-medium text-gray-900 mb-2">
        <%= @result.monk_description %>
      </p>

      <% if user_signed_in? %>
        <div class="">
          <%= link_to "もう一度診断する", root_path, class: 'mt-9 inline-block bg-blue-200 hover:bg-blue-400 text-black font-semibold py-3 px-6 rounded-md shadow-md transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-50' %>
        </div>
      <% else %>
       
          <%= link_to "もう一度診断する", root_path, class: 'mt-9 inline-block bg-blue-200 hover:bg-blue-400 text-black font-semibold py-3 px-6 rounded-md shadow-md transition duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-opacity-50' %>
        <div class="pt-5 hover:font-bold transition-all duration-400">
          <%= link_to "ユーザー登録であなたの訪れた場所を共有する", new_user_registration_path %>
        </div>
      <% end %>

    </div>
  </div>

  <div class="flex justify-end py-6">
    <div>
      <p class="text-sm  py-2 px-2">結果をシェアする</p>
    </div>
    <a href="https://twitter.com/intent/tweet?text=あなたの診断結果は...%0A%0A<%= ERB::Util.url_encode(@result.name) %>(<%= ERB::Util.url_encode(@result.title) %>)%0A&hashtags=診断,名僧,歴史&url=<%= ERB::Util.url_encode(root_url) %>"
        target="_blank" rel="nofollow">
      <i class="fa-brands fa-square-x-twitter fa-2x"></i>
    </a>
  </div>
</div>